package com.example.gramclient.utils

object RoutesName {
    const val SPLASH_SCREEN="SPLASH_SCREEN"
    const val MAIN_SCREEN="MAIN_SCREEN"
    const val AUTH_SCREEN="AUTH_SCREEN"
    const val IDENTIFICATION_SCREEN="IDENTIFICATION_SCREEN"
    const val SETTING_SCREEN="SETTING_SCREEN"
    const val SETTING_LANGUAGE_SCREEN="SETTING_LANGUAGE_SCREEN"
    const val SETTING_REGION_SCREEN="SETTING_REGION_SCREEN"
    const val SETTING_SELECT_REGION_SCREEN="SETTING_SELECT_REGION_SCREEN"
    const val MY_ADDRESSES_SCREEN="MY_ADDRESSES_SCREEN"
    const val ADD_ADDRESSES_SCREEN="ADD_ADDRESSES_SCREEN"
    const val SUPPORT_SCREEN="SUPPORT_SCREEN"
    const val EDIT_ADDRESSES_SCREEN="EDIT_ADDRESSES_SCREEN"
    const val PROFILE_SCREEN="PROFILE_SCREEN"
    const val MESSAGE_SCREEN="MESSAGE_SCREEN"
    const val ABOUT_SCREEN="ABOUT_SCREEN"
    const val ORDERS_HISTORY_SCREEN="ORDERS_HISTORY_SCREEN"
    const val PROMO_CODE_SCREEN="PROMO_CODE_SCREEN"
    const val ORDER_EXECUTION_SCREEN="ORDER_EXECUTION_SCREEN"
    const val SEARCH_DRIVER_SCREEN="SEARCH_DRIVER_SCREEN"
    const val SEARCH_ADDRESS_SCREEN="SEARCH_ADDRESS_SCREEN"
}